# Generated by Django 5.2.5 on 2025-09-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_item_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='preco',
        ),
        migrations.AddField(
            model_name='item',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('bebida', 'Bebida'), ('comida', 'Comida')], max_length=10),
        ),
    ]
