# Generated by Django 5.2.5 on 2025-09-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_remove_item_preco_item_valor_alter_item_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='nome',
            new_name='produto',
        ),
    ]
