# Generated by Django 5.2.5 on 2025-09-01 12:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='token_qr',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
