# Generated by Django 5.2.5 on 2025-09-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='item',
            new_name='produto',
        ),
    ]
